version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8010:8010"
