version: "3"
services:
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        stdin_open: true
        volumes: 
            - /app/node_modules
            - ./client:/app 
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - "8080:80"